### ISSUE TITLE
error on vimisort

### ISSUE THREAD

**Issue by alvesadrian** [fisadev/fisa-vim-config#111]
~ ❯❯❯ vim a
Error detected while processing ~/.vim/plugged/vim-isort/plugin/python_vimisort.vim:
line  104:
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/usr/lib/python3.7/site-packages/isort/__init__.py", line 26, in <module>
    from .isort import SortImports  # noqa: F401
  File "/usr/lib/python3.7/site-packages/isort/isort.py", line 41, in <module>
    from .finders import FindersManager
  File "/usr/lib/python3.7/site-packages/isort/finders.py", line 24, in <module>
    from pip._internal.download import PipSession
  File "/usr/lib/python3.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 22, in <module>
    from pip._internal.utils.hashes import STRONG_HASHES
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/hashes.py", line 10, in <module>
    from pip._internal.utils.misc import read_chunks
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 21, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    for dist in working_set
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3154, in <genexpr>
    for dist in working_set
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2661, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2187, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2104, in _handle_ns
    loader = importer.find_module(packageName)
AttributeError: module 'vim' has no attribute 'find_module'
Press ENTER or type command to continue

**Comment by fisadev** [comment]
(closing, old issue fixed in current versions)
